//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParamedicMedicosPrestaciones.WSOperativaClientes {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="WSOperativaClientes.ClientesOperativosSoap")]
    public interface ClientesOperativosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.ClientesOperativos.GetFinalizados", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetFinalizados(long pUsr, long pDes, long pHas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebServices.ClientesOperativos.GetOperativaEnCurso", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetOperativaEnCurso(long pUsr);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClientesOperativosSoapChannel : ParamedicMedicosPrestaciones.WSOperativaClientes.ClientesOperativosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientesOperativosSoapClient : System.ServiceModel.ClientBase<ParamedicMedicosPrestaciones.WSOperativaClientes.ClientesOperativosSoap>, ParamedicMedicosPrestaciones.WSOperativaClientes.ClientesOperativosSoap {
        
        public ClientesOperativosSoapClient() {
        }
        
        public ClientesOperativosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientesOperativosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientesOperativosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientesOperativosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetFinalizados(long pUsr, long pDes, long pHas) {
            return base.Channel.GetFinalizados(pUsr, pDes, pHas);
        }
        
        public System.Data.DataSet GetOperativaEnCurso(long pUsr) {
            return base.Channel.GetOperativaEnCurso(pUsr);
        }
    }
}
